Responsive Text Pages
nestauk/eurito_indicators pull request #12
Opened 2021-02-15 18:12 UTC by saabi

Closes #8

2021-02-18 19:05 UTC, mindrones requested changes
some changes required

2021-02-18 19:05 UTC, mindrones commented on netlify.toml
> +	environment = { NODE_VERSION = "15.8.0" }
since we're here, I'd use tabs only, as it seems to work (yaml doesn't support tabs for some reason)

2021-02-18 19:05 UTC, mindrones commented on src/node_modules/app/components/ScreenGauge.svelte
> +	// const dispatch = createEventDispatcher();
I'd leave the TODO comment (`TODO Support stores AND events too?`), removing the rest

2021-02-18 19:05 UTC, mindrones commented on src/node_modules/app/components/ScreenGauge.svelte
> +		// dispatch('resize', flags); // event support
leftover

2021-02-18 19:05 UTC, mindrones commented on src/node_modules/app/components/ScreenGauge.svelte
> +					: 'large'
I'd rename `sizeId` to `classes`

2021-02-18 19:05 UTC, mindrones commented on src/node_modules/app/components/ScreenGauge.svelte
> +	>x</span>
I'd use `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz` and I'd then divide by 52

2021-02-18 19:05 UTC, mindrones commented on src/routes/_layout.svelte
> +	$: rootStyle && ( rootStyle.fontSize = `${$fontScaling * 16}px`);
we have discussed about:
- making this portion into an utility to import here
- measuring the root font size on mount

2021-02-22 18:07 UTC, mindrones commented on src/node_modules/app/components/ScreenGauge.svelte
> +	]);
Here we could use [`getTruthyValuesKeys`](https://nestauk.github.io/svizzle/jsDocBuild/module-@svizzle_utils_object-array.html#.getTruthyValuesKeys):

```js
const getClasses = _.pipe([getTruthyValuesKeys, _.joinWith(' ')]);
```

2021-02-22 20:00 UTC, mindrones approved these changes
Great job! 👌

2021-02-22 20:00 UTC, mindrones commented on src/node_modules/app/components/ScreenGauge.svelte
> +	>x</span>
to be implemented in `@svizzle/ui`

2021-02-22 20:00 UTC, mindrones commented on src/routes/_layout.svelte
> +		&& (rootStyle.fontSize = `calc(${defaultFontSize} * ${$fontScaling})`);
we have some discussions going on about making this modular, but I'm going to approve as we need some more discussions

2021-02-22 20:02 UTC, saabi commented on src/node_modules/app/components/ScreenGauge.svelte
> +	>x</span>
I'd also make it an exported prop to allow users to use their own string, which may help with language support.

2021-02-22 20:56 UTC, merged