Added `mdsvex` module
nestauk/eurito_indicators pull request #191
Opened 2021-09-06 03:03 UTC by saabi

Closes #189

2021-09-09 12:19 UTC, mindrones requested changes
first pass, mostly just formatting

2021-09-09 12:19 UTC, mindrones commented on ui/rollup.config.js
minor, no extra blank line needed here

2021-09-09 12:19 UTC, mindrones commented on ui/src/node_modules/app/components/md/a.svelte
> +    import Link from '@svizzle/ui/src/Link.svelte';
we need to use tabs everywhere rathenr than spaces

2021-09-09 12:19 UTC, mindrones commented on ui/src/node_modules/app/components/md/h5.svelte
> +<h4 {...$$props}><slot/></h4>
minor, I'd have the slot on a new line for readability in these components

2021-09-09 12:19 UTC, mindrones commented on ui/src/routes/Accessibility.svx
> +	} from 'app/config';
I think these can go on a single line

2021-09-09 12:19 UTC, mindrones commented on ui/src/routes/Index.svx
> +	const repoUrl = 'https://github.com/nestauk/eurito_indicators';
I'd use a frontmatter

2021-09-09 12:19 UTC, mindrones commented on ui/src/routes/Methodology.svx
> +</script>
I'd use a frontmatter

2021-09-09 12:19 UTC, mindrones commented on ui/src/routes/_layout.svelte
> +
I'd remove this extra blank line

2021-09-09 12:19 UTC, mindrones commented on ui/src/node_modules/app/components/CTA.svelte
> +   	import {_screen} from '@svizzle/ui/src/gauges/screen/ScreenGauge.svelte';
we need to use tabs only

2021-09-09 12:19 UTC, mindrones commented on ui/src/node_modules/app/components/CTA.svelte
> +	}
this block needs indentation

2021-09-09 12:19 UTC, mindrones commented on ui/src/node_modules/app/components/CTA.svelte
> +<script>
I'd probably call this component `ResponsiveFlex`, which seems generic enough and could be then ported to `@svizzle/ui`

2021-09-09 12:19 UTC, mindrones commented on ui/src/routes/guides/indicators.svelte
> +
extra blank line to be removed

2021-09-09 12:19 UTC, mindrones commented on ui/src/routes/guides/indicators.svelte
> +	import LinkButton from '@svizzle/ui/src/LinkButton.svelte';
we need to visually separate npm imports from local imports

2021-09-09 12:19 UTC, mindrones commented on ui/src/routes/index.svelte
>  	import LinkButton from '@svizzle/ui/src/LinkButton.svelte';
we need to visually separate npm imports from local imports

2021-09-09 12:19 UTC, mindrones commented on ui/src/routes/methodology.svelte
> +
extra blank line to be removed

2021-09-09 18:01 UTC, mindrones requested changes
pass 2:
- mostly formatting
- `ui/src/routes/info/disclaimer.svelte` still needs converting
- I'd move svx files in a dir like [1]

[1]
```
routes/
  _content/
    info/*.svx
    guides/*.svx
    *.svx
```

2021-09-09 18:01 UTC, mindrones commented on ui/rollup.config.js
> +import {unescape_code} from './src/node_modules/app/utils/unescape-inlineCode';
minor, we need to remove the extra line and sort by filepath

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/components/ResponsiveFlex.svelte
> +   	import {_screen} from '@svizzle/ui/src/gauges/screen/ScreenGauge.svelte';
there's a mix of tab and spaces here

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/components/ResponsiveFlex.svelte
> +	.cta {
I'd rename this class to `ResponsiveFlex` to ease DOM inspection

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/components/md/_layout.svelte
> +   	import {_screen} from '@svizzle/ui/src/gauges/screen/ScreenGauge.svelte';
there's a mix of tab and spaces here

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/components/md/a.svelte
> +	$: type = href && href.startsWith('http') && 'external' || null;
I'd add an extra line in between

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/components/md/code.svelte
> +<code {...$$props}><slot/></code>
I'd indent the slot here

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/components/md/h1.svelte
> + 	h1 {
there's a mix of tab and spaces here

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/components/md/h2.svelte
> + 	h2 {
there's a mix of tab and spaces here

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/utils/unescape-inlineCode.js
> +}
we need to change spaces for tabs here

2021-09-09 18:01 UTC, mindrones commented on ui/src/node_modules/app/components/md/_layout.svelte
> +<script context="module">
I'd rename this dir to `ui/src/node_modules/app/components/mdsvex`

2021-09-09 18:01 UTC, mindrones commented on ui/src/routes/Accessibility.svx
> +	import {zipUrl} from 'app/utils/assets';
we need to split npm imports from local imports here

2021-09-09 18:01 UTC, mindrones commented on ui/src/routes/guides/a11ymenu.svelte
>  		from '@svizzle/ui/src/gauges/screen/ScreenGauge.svelte';
this seems to be unused

2021-09-09 18:01 UTC, mindrones commented on ui/src/routes/guides/indicators.svelte
> +	import theme from 'app/theme';
we need to split npm/local imports

2021-09-09 18:01 UTC, mindrones commented on ui/src/routes/methodology.svelte
>  	import theme from 'app/theme';
split npm/local imports

2021-09-09 19:24 UTC, saabi commented on ui/src/node_modules/app/components/md/code.svelte
> +<code {...$$props}><slot/></code>
The issue here it's that a code block will preserve whitespace. We can do the following however:
```
<code {...$$props}><!--
    --><slot/><!--
--></code>
```

2021-09-10 16:10 UTC, mindrones approved these changes
Great job, good to merge! 💯

2021-09-13 12:24 UTC, merged