217 make indicators clean
nestauk/eurito_indicators pull request #218
Opened 2021-12-16 10:36 UTC by Juan-Mateos

Closes #217 
Closes #111

2021-12-16 12:37 UTC, mindrones requested changes
First pass: we need to address points 1, 2, 3, 4, 5 everywhere.
I pointed them in a good part of the PR but it seems pointless to continue for now, I'll check them all aftere these points will be tackled

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/ai_covid_count.csv
> +3,2020,NUTS,2016,AT130,3,2
(1) We need to remove the extra first column here

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/ai_covid_count.json
> +"region_type",
(2) It would be useful if you could indent the schemas to facilitate reading/reviewing, e.g. see below.

```
{
	"api_type": "MySQL",
	"data_date": "2021/07/01",
	"description": "Number of preprints related to an AI category",
	"endpoint_url": "DAPS",
	"framework_group": "publications",
	"is_experimental": true,
	"order": [
		"year",
		"region_type",
		"region_year_spec",
		"region_id",
		"region_level",
		"value.id"
	],
	"region_types": [
		"NUTS"
	],
	"schema": {
		"region_id": "string",
		"region_level": "int",
		"region_type": "string",
		"region_year_spec": "int",
		"value": {
			"data_type": "int",
			"format": ".1f",
			"id": "ai_covid_count",
			"label": "Number participations in AI applications to Covid-19 preprints"
		},
		"year": {
			"data_type": "int",
			"label": "Year"
		}
	},
	"source_name": "Nesta",
	"source_url": "https://github.com/nestauk/eurito_indicators",
	"subtitle": "Number participations in AI applications to Covid-19 preprints by institutions in the location (papers identified through a semantic analysis of abstract topics",
	"title": "Number of participations in AI applications to Covid-19 preprints",
	"date": "2021-12-15"
}
```

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/ai_covid_count.json
> +"api_doc_url": "DAPS",
(3) `api_doc_url` is optional so if we don't have an actual URL for that fieltd, then I'd skip it

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/antiviral_drugs_lq.json
> +"id": "antiviral_drugs_count",
(4) This `id` seems incorrect

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/deep_learning_count.json
> +"date": "2021-12-16"
(5) `date` is not a field in the schema.
If this was supposed to be `data_date`, then we have a duplicate info here

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/detection_diagnosis_lq.json
> +"id": "detection_diagnosis_count",
See (4)

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/detection_diagnosis_lq.json
> +"id": "detection_diagnosis_count",
see (4)

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/detection_sequencing_lq.json
> +"id": "detection_sequencing_count",
See (4)

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/education_lq.json
> +"id": "education_count",
See (4)

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/detection_diagnosis_count.json
> +"date": "2021-12-16"
See (5)

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/education_lq.json
> +"date": "2021-12-16"
See 5

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/education_lq.json
> +"id": "education_count",
See 4

2021-12-16 12:37 UTC, mindrones commented on ds/outputs/data/processed/_articles/genetic_analysis_lq.json
> +"id": "genetic_analysis_count",
See 5

2021-12-16 15:58 UTC, Juan-Mateos commented
- [ ] Removed the trailing index columns from indicators
- [ ] Removed the `date` variable
- [ ] Removed the `api_doc_url` variable
- [ ] Indented the json
- [ ] Changed suffix in `lq` indicators

2021-12-17 18:04 UTC, mindrones requested changes
I have:
- deleted all folders like `ds/outputs/data/processed/_*` (we were prefixing folders with an underscore to separate them from new indicators)
- deleted `ds/outputs/data/processed/sdg/`

We need to rename `ds/outputs/data/processed/_articles/` to `ds/outputs/data/processed/articles/`, but I'll leave that to you as it probably has implications on your scripts.

Apart from that I left just a few notes about what's left to be changed below.

2021-12-17 18:04 UTC, mindrones commented on ds/outputs/data/processed/_articles/ai_covid_count.json
> +  "api_doc_url": "DAPS",
a) there are still occurrences of `"api_doc_url": "DAPS",` in files:
- `articles/ai_covid_count.json`
- `articles/artificial_intelligence_count.json`
- `articles/arxiv_count.json`
- `articles/biorxiv_count.json`
- `articles/cord_count.json`
- `articles/deep_learning_count.json`
- `articles/medrxiv_count.json`

2021-12-17 18:04 UTC, mindrones commented on ds/outputs/data/processed/_articles/ai_covid_count.json
> +  "endpoint_url": "DAPS",
b) `endpoint_url` seems to be to `"DAPS"` in all jsons in `_articles/`.

These should be a URL, a list of URLs, or an object `{key, URL}`

2021-12-17 18:04 UTC, mindrones commented on ds/outputs/data/processed/_articles/schema/articles_ai_base_schema 2.json
> +{
Because of how the script that collects the data and prepares it for the consumption, we need not to have non-data-related files in `ds/outputs/data/processed/**/*`, so we'd need to move `ds/outputs/data/processed/_articles/schema/*` somewhere else outside of `ds/outputs/data/processed/`.

Note that for this reason I haven't reviewed any of the files in `ds/outputs/data/processed/_articles/schema/*`.

2021-12-18 16:34 UTC, Juan-Mateos commented
I have:
- [ ] Moved the schema templates to `data/schema/articles`
- [ ] Changed the `make_indicators_final.py` script to read schema from the right folders and output it into the right folders
- [ ] Removed `endpoint_url` from the schema - it is unclear what these would be when we are fetching data from MySQL databases in DAPs
- [ ] Removed `API_doc_url` from the schema 
- [ ] Made titles less verbose as discussed e.g. changed from "Number of article participations in AI" to "AI articles (count)" 
- [ ] Re-ran the script and saved article tables and schema in `data/processed/articles`

2021-12-18 18:07 UTC, mindrones requested changes
Now that I have been able to run `make_index`, I see that we have to shorten some `subtitle`s (see below).

We also need to delete `ds/outputs/data/processed/_articles`.

<details>
<summary>Copy to shorten:</summary>

```
-- id: ai_covid_count
 |- subtitle: 161
-- id: airborne_count
 |- subtitle: 149
-- id: airborne_lq
 |- subtitle: 240
-- id: antibodies_count
 |- subtitle: 151
-- id: antibodies_lq
 |- subtitle: 242
-- id: antiviral_drugs_count
 |- subtitle: 156
-- id: antiviral_drugs_lq
 |- subtitle: 247
-- id: artificial_intelligence_count
 |- subtitle: 157
-- id: deep_learning_count
 |- subtitle: 147
-- id: detection_diagnosis_count
 |- subtitle: 160
-- id: detection_diagnosis_lq
 |- subtitle: 251
-- id: detection_sequencing_count
 |- subtitle: 161
-- id: detection_sequencing_lq
 |- subtitle: 252
-- id: education_count
 |- subtitle: 150
-- id: education_lq
 |- subtitle: 241
-- id: genetic_analysis_count
 |- subtitle: 157
-- id: genetic_analysis_lq
 |- subtitle: 248
-- id: healthcare_count
 |- subtitle: 151
-- id: healthcare_lq
 |- subtitle: 242
-- id: hospitalisation_count
 |- subtitle: 156
-- id: hospitalisation_lq
 |- subtitle: 247
-- id: image_detection_count
 |- subtitle: 156
-- id: image_detection_lq
 |- subtitle: 247
-- id: impact_studies_2_count
 |- subtitle: 157
-- id: impact_studies_2_lq
 |- subtitle: 248
-- id: impact_studies_3_count
 |- subtitle: 157
-- id: impact_studies_3_lq
 |- subtitle: 248
-- id: impact_studies_count
 |- subtitle: 155
-- id: impact_studies_lq
 |- subtitle: 246
-- id: indirect_impacts_count
 |- subtitle: 157
-- id: indirect_impacts_lq
 |- subtitle: 248
-- id: lockdown_social_distancing_2_count
 |- subtitle: 169
-- id: lockdown_social_distancing_2_lq
 |- subtitle: 260
 |- title: 64
-- id: lockdown_social_distancing_count
 |- subtitle: 167
-- id: lockdown_social_distancing_lq
 |- subtitle: 258
 |- title: 62
-- id: mental_health_count
 |- subtitle: 154
-- id: mental_health_lq
 |- subtitle: 245
-- id: patient_impact_count
 |- subtitle: 155
-- id: patient_impact_lq
 |- subtitle: 246
-- id: population_impact_count
 |- subtitle: 158
-- id: population_impact_lq
 |- subtitle: 249
-- id: prediction_count
 |- subtitle: 151
-- id: prediction_lq
 |- subtitle: 242
-- id: repurposed_treatments_count
 |- subtitle: 162
-- id: repurposed_treatments_lq
 |- subtitle: 253
-- id: serology_count
 |- subtitle: 149
-- id: serology_lq
 |- subtitle: 240
-- id: smoking_cancer_count
 |- subtitle: 155
-- id: smoking_cancer_lq
 |- subtitle: 246
-- id: social_media_count
 |- subtitle: 153
-- id: social_media_lq
 |- subtitle: 244
-- id: trials_count
 |- subtitle: 147
-- id: trials_lq
 |- subtitle: 238
-- id: vaccination_programmes_count
 |- subtitle: 163
-- id: vaccination_programmes_lq
 |- subtitle: 254
-- id: vaccines_count
 |- subtitle: 149
-- id: vaccines_lq
 |- subtitle: 240
-- id: variants_count
 |- subtitle: 149
-- id: variants_lq
 |- subtitle: 240
```

</details>

2021-12-20 18:48 UTC, mindrones commented
I noticed that there are a number of texts starting with `Number participations` (e.g. `Number participations in AI applications to Covid-19 preprints`): assuming it it was supposed to be `Number of participations`.

2021-12-23 15:54 UTC, mindrones approved these changes
As we agreed to publish to staging asap, I've fixed `Number participations` -> `Number of participations`.
We can shorten the copy later on in a [specific issue](https://github.com/nestauk/eurito_indicators/issues/219).
Approving & merging.

2021-12-23 15:58 UTC, merged

2021-12-23 15:58 UTC, mindrones approved these changes